### ISSUE TITLE
Slow to register occupancy - any way to improve?

### ISSUE THREAD

**Issue by twynne** [oznu/homebridge-unifi-occupancy-sensor#10]
Hi there,

This sensor plugin is working without issue, but I note that it seems to take a very long time after I've (re)joined the network to register the fact, as well as a long time after leaving before it realises.

I believe I've seen somewhere in the docs that it can take up to 15 minutes to realise an occupant (device) has left, but should it be the same when a device joins?  Is this just down to the frequency of polling the Unifi USG, or something else?  If so any way to increase the frequency of checking?

Thanks!  👍

**Comment by oznu** [comment]
Device join triggers should be no more than 10 seconds based on my own experience.

This plugin doesn't actually poll the controller as it's primary mechanism of detecting connecting devices, it connects to the controller event log web socket and listens for connection notifications. This usually results in near-instant occupancy triggers without putting any load on the controller.

It does do a manual check every 30 minutes in case it failed to receive the notification for whatever reason.

Perhaps the event log notifications have changed in a newer version than what I run, and the plugin is only polling? How do the logs look? Unifi Controller version?

**Comment by twynne** [comment]
Hi there,

Thanks for the very quick response.  It’s controller v5.9.29 connecting to a USG3.

If you mean the home bridge logs (as opposed to Unify), I don’t see anything unusual happening for this plugin.  I have been finding my home bridge instance restarting itself periodically, but unfortunately the logs are destroyed when the server restarts so I have little to go on at present!  Anything else I should check?

Cheers


Tom

**Comment by oznu** [comment]
Are you using a UniFi AP as well? Or do you have a different brand AP connected to the USG?

**Comment by twynne** [comment]
Looking further at Ubnt event logs vs what was reported on Homebridge, my phone (the trigger device) left the network at 1:20pm today and re-joined at 1:54pm.  The notification from Homebridge was reported at 2:14pm.  That’s 20 minutes after the device joined, so I’m inclined to think your ’30 minute’ theory may be correct.

Any other reason there would be such a delay?  I’ll test again in a second and see what is captured in the Homebridge log (assuming it doesn’t crash in the interim!)

Cheers


Tom

**Comment by twynne** [comment]
> Are you using a UniFi AP as well? Or do you have a different brand AP connected to the USG?

No, I'm using a different wireless mesh system (Linksys Velop) which is connected ethernet backhaul to the USG and in bridge mode.

**Comment by twynne** [comment]
Hi there,

Further update... I now know the source of the Homebridge crashing (Harmony) so that's unrelated.  Have you had any further thoughts on why this is taking so long to register?  On assumption that the method of access for the '30 minute' check is the same as the other, I'm struggling to see why the former would work and the other not.

Appreciate any insight you can offer.

Thanks!

**Comment by twynne** [comment]
For what it's worth, I can see that the entries from this plugin in the log are exactly 30 minutes apart (no occupancy and then occupancy detected) so it is the 'fallback' method registering occupancy.

**Comment by gold2605** [comment]
Hello, I have the same problem. It takes a long time for a new device (cell phone when someone comes home) to be detected. It fits with the max. 30 min. I use the complete Unifi system (USG and AP from Unifi). The whole thing worked great, because I had compiled a door lock when coming home. I have the Unifi controller on the latest version 5.9.29.
Is there a solution?

Thank you
