### ISSUE TITLE
Guest Occupancy Sensor

### ISSUE THREAD

**Issue by DSchumacher2104** [oznu/homebridge-unifi-occupancy-sensor#15]
Is it possible to add an occupancy sensor which shows, if any guest is connected to Guest-(W)LAN, without watching or even knowing their MAC-Addresses? It could be useful in automations to kown, if any guest is at home

**Comment by AlfaJackal** [comment]
That would be a killer...!

**Comment by tickez** [comment]
Quickly hacked this together: homebridge-unifi-guest-occupancy-sensor based on @oznu 's nice library.

**Comment by creedda** [comment]
++
