### ISSUE TITLE
Feature Request: Specify Delay Before Timeout

### ISSUE THREAD

**Issue by brodkin** [oznu/homebridge-unifi-occupancy-sensor#16]
Hello, great project!

I've been using this for a couple months now, but I run into an issue every once in a while where I am the only person home and my phone briefly disconnects from the wifi and suddenly my automations are triggered. In a future update I'd be very appreciative of a feature that allows us to specify how long the accessory waits for any user to reconnect before it turns off. For my use case this would mean that I could specify that the system waits 90 seconds for, say, my phone to restart before triggering any automations.

Thank you!

**Comment by WRTHacker** [comment]
That's exactley what I need,, too.
The plugin works very well, but when moving in my home, and roaming occurs from one AP to another, the occupancy switches to away and than back. An timeout to specify was a perfect extension.

**Comment by jeloneal** [comment]
I second that request. In my 3 story house it often happens that automations get triggered while roaming from one AP to the other with my phone in the pocket.

A configurable timeout or configurable number of subsequent occurrings of the triggering event would be a welcome addition to the plugin.

**Comment by PetersenLars** [comment]
This seems like something I could definitely use. Now my thermostat turns off every time my phone roams to a different AP. Any update on this?
