### ISSUE TITLE
2FA Authentication Issues

### ISSUE THREAD

**Issue by mneumark** [oznu/homebridge-unifi-occupancy-sensor#18]
I recently started getting authentication issues (was working until a few weeks ago). Here is an example of the message I'm getting:
```
11/23/2019, 3:56:09 PM] [UniFi Occupancy Sensor] UniFi Events: Login Failed 400 - {"meta":{"rc":"error","msg":"api.err.Ubic2faTokenRequired"},"data":[]}
```

Is there a way to make this plugin work without disabling two factor authentication? If so, it should probably tell you how to go about it. If not, it should have a warning about it.

Thanks!

**Comment by mneumark** [comment]
Just a note if it helps: It seems the field it is expecting along with `username` and `password` and `strict` is `ubic_2fa_token`. Not sure if there is another way. I tried making the call with my 2FA code in Postman and it worked. I tried passing one of the backup codes I have as the `ubic_2fa_token` but it didn't work.

**Comment by mneumark** [comment]
@oznu Been a couple weeks so just checking in to see if you had a chance to read this.

Thanks!

**Comment by simonlock** [comment]
I had the same problem until yesterday but just made a second "read-only account" with a strong password for homebridge use. The 2FA seems only to be applied to the super admin account. This plugin is working for me now.

**Comment by oznu** [comment]
A read only account is the way to go here.
