### ISSUE TITLE
Adding multiple MACs

### ISSUE THREAD

**Issue by Kimovitzh** [oznu/homebridge-unifi-occupancy-sensor#2]
Hi.
I've got the accessory running and watching a MAC and it works. It triggers the "sensor" in HomeKit.
Now I want another "sensor" but can't figure out how to do this.

Can someone guide me?

TL;DR
Got one "MAC sensor" running in HomeKit, now I want one more. How?

**Comment by oznu** [comment]
Does the example in this comment answer your question? https://github.com/oznu/homebridge-unifi-occupancy-sensor/issues/1#issuecomment-333694893

**Comment by Kimovitzh** [comment]
Creating multiple sensors does seem to work now. But multiple MACs on same sensor dosen't work, it only looks at the first MAC in the [ "watch": ["44:00:00:00:00:00", "30:00:00:00:00:00", "22:00:00:00:00:00"], ] Array

**Comment by oznu** [comment]
Hi @Kimovitzh,

I have tested the plugin and multiple macs in an array definitely works.

I did find an issue which would have resulted in devices connected to guest wifi networks not triggering the occupancy sensor instantly - which I have fixed in 0.0.8.
