### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by tibmeister** [oznu/homebridge-unifi-occupancy-sensor#23]
**Describe The Bug:**
UniFi Events: Error (52) - write EPROTO 140270975547264:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 70

* **Node.js Version**: 12.18.3
* **NPM Version**: 6.14.7
* **Homebridge Version**: 1.1.2
* **Homebridge Plugin Version**: 1.0.0
* **Homebridge Config UI X Plugin Version**: 4.25.2
* **Operating System**: Ubuntu 18.04.5 LTS

**Comment by oznu** [comment]
The TLSv1 protocol is disabled by default in Node.js 12 or later. 

You can enable it by adding `--tls-min-v1.0` to your NODE_OPTIONS env var:

![image](https://user-images.githubusercontent.com/3979615/106108150-fb5e0480-619b-11eb-80ca-edd8ed976f19.png)
