### ISSUE TITLE
Feature Request: Add a label to the watched and monitored devices

### ISSUE THREAD

**Issue by marcgetter** [oznu/homebridge-unifi-occupancy-sensor#24]
**Is your feature request related to a problem? Please describe:**
No

**Describe the solution you'd like:**
I'd like to be able to know in HomeKit which user is being shown as at home.

**Describe alternatives you've considered:**
Changing in homekit, but homekit doesn't always retain details and locations of devices from homebridge

**Comment by twynne** [comment]
This would be incredibly useful, especially as certain 'mobile' devices are being upgraded practically on an annual basis.  It's a pain trying to work out which ones are which from the MAC address.

**Comment by sadiq81** [comment]
Why is this not supported yet?
