### ISSUE TITLE
5 monitored devices suddenly not detected anymore

### ISSUE THREAD

**Issue by AdeTheux** [oznu/homebridge-unifi-occupancy-sensor#26]
**Describe Your Problem:**
Using this plugin for well over a year now, but since a few days, none of the monitored devices are detected anymore. They are all in the house, connected to the AP. Plugin is in any mode.
"0 monitored devices found. The accessory is in ANY mode so not triggering occupancy."

What could cause that sudden change of behaviour?
Thanks

**Logs:**
```
Not crashing, so no logs. See above.
```

**Homebridge Config:**

```json
	{
    "accessory": "UniFi Occupancy Sensor",
    "name": "Occupancy Sensor",
    "unifi": {
      "controller": "https://unifi.link.com:8443",
      "username": "email@domain.com",
      "password": "password",
      "site": "xyzxyzxyz",
      "secure": true
    },
    "monitor": [
      {
        "iPhone": "B2:4D:...",
        "Arnaud-MBP": "F8:FF:...",
        "Lisas-MBP": "6c:96:...",
        "Samsung-Galaxy-S7": "4c:66:...",
        "AppleWatch": "D6:17:..."
      }
    ],
      "watchGuests": true,
      "interval": 1800,
      "mode": "any"
  }
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 14.14
* **NPM Version**: 6.14.8
* **Homebridge Version**: 1.1.6
* **Homebridge Plugin Version**: 1.00
* **Homebridge Config UI X Plugin Version**: not installed
* **Operating System**: Always-on Android tablet running Termux.

**Comment by palletodap** [comment]
Im not an expert at all, but i think there could be a couple things maybe.

It looks like you have mixed the setup of "watch" and "monitored".

If you wanna use monitored, i think it should be like this:
"monitor": [
      {
        "device": "B2:4D:..."
      },
      {
        "device": "F8:FF:..."
      },
      {
        "device": "6c:96:..."
      },
      {
        "device": "4c:66:..."
      },
      {
        "device": "D6:17:..."
      }
    ]
