### ISSUE TITLE
Multiple MAC issue.

### ISSUE THREAD

**Issue by hjdhjd** [oznu/homebridge-unifi-occupancy-sensor#3]
Great sensor concept. The challenge I have is that detection doesn't seem to work correctly with multiple MACs.

If I list one MAC in the "watch" array, everything works as expected and as the device connects / disconnects it gets properly picked up.

If I have two MACs in the "watch" array, the behavior is very inconsistent. What I've done to test this is setup my config.json with one MAC, monitor the homebridge log file and then allow the MAC on the network and then remove it from the network...it gets picked up properly by the occupancy sensor.

Repeat the same experiment with two MACs in the "watch" array...it will pretty consistently show one device connected even when NO devices are on the network that are being watched for.

I tested this further by restarting homebridge with no devices on the network and the UCK event log showing that the devices were in fact not on the network...and still the occupancy sensor logs that it detects a device on the network when it shouldn't.

Happy to help debug this further...my sense is something is a bit off with how you're matching multiple watched MACs.

I'm running UniFi 5.7.20, for reference.

**Comment by oznu** [comment]
Hi @hjdhjd,

A few people have raised this, however each time I have been unable to replicate the issue.

I have just published a new version that has the ability to show debug logging.

If you start homebridge with the `DEBUG=unifi` environment variable you will be able to see exactly which MAC addresses are triggering occupancy and other verbose logging that should explain what's going on. 

```
DEBUG=unifi homebridge
```

Example output:

```
  unifi Getting list of connected clients from UniFi Controller... +0ms
[2018-4-13 19:35:12] [Occupancy Sensor] UniFi Events: Connected (1) - wss://unifi.controller/wss/s/default/events
  unifi 5 devices are currently connected to the UniFi network, checking each one to see if any are on the watch list... +883ms
  unifi Device [60:01:94:1a:c9:eb] HOSTNAME: "daikin-thermostat-2" , GUEST: "false", SSID: "My WiFi" +0ms
  unifi Device [60:01:94:1a:c9:eb] Ignoring. Not on the watch list. +0ms
  unifi Device [a0:20:a6:08:35:51] HOSTNAME: "homebridge-fan" , GUEST: "false", SSID: "My WiFi" +0ms
  unifi Device [a0:20:a6:08:35:51] Ignoring. Not on the watch list. +0ms
  unifi Device [2c:3a:e8:0f:29:a7] HOSTNAME: "daikin-thermostat-1" , GUEST: "false", SSID: "My WiFi" +0ms
  unifi Device [2c:3a:e8:0f:29:a78] Ignoring. Not on the watch list. +0ms
  unifi Device [42:3a:11:f0:3e:61] HOSTNAME: "iPhone" , GUEST: "false", SSID: "My WiFi" +0ms
  unifi Device [42:3a:11:f0:3e:61] is NOT connected to a guest network. +1ms
  unifi Device [42:3a:11:f0:3e:66] Device is on the watch list. Going to trigger occupancy. +0ms
  unifi Device [42:6d:57:4b:99:6f] HOSTNAME: "Laptop" , GUEST: "false", SSID: "My WiFi" +0ms
  unifi Device [42:6d:57:4b:99:6f] Ignoring. Not on the watch list. +0ms
  unifi Monitored devices found: [ '42:3a:11:f0:3e:61' ] +0ms
[2018-4-13 19:35:12] [Occupancy Sensor] 1 monitored device(s) found
```

Whenever any device connects or disconnects the event will be logged: 

```
  unifi Device Disconnected Event Received from UniFi Controller: User[a0:20:a6:08:35:51] disconnected from "My WiFi" (61d 22h connected, 30.99M bytes, last AP[xx:xx:xx:xx:xx:xx]) +5m

  unifi Device Connected Event Received from UniFi Controller: User[a0:20:a6:08:35:51] has connected to AP[xx:xx:xx:xx:xx:xx] with ssid "My WiFi" on "channel 6(ng)" +25s
```

Disconnects can take upto 15 minutes for the UniFi controller to acknowledge, you can test it more quickly by clicking the "Reconnect" button next to the device on the client list.

I am still running 5.6.36 and have not tested this on 5.7.x yet. If you can spot an error with how this is matching MACs please share the logs and I'll do my best to fix the issue.
