### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by hfagelnour** [oznu/homebridge-unifi-occupancy-sensor#30]
the plugin was working more than fine on unifi OS after applying the "Patch" 
as soon as i update to ver 2.0.0 it stopped working and i am getting this in the log
"ERROR: Failed to check occupancy: Cannot read property 'length' of undefined"
help pls

**Comment by aschneider** [comment]
I have had the same issue. 

The documentation states you need to add  "unifios": true to the config, if you are already using unify os, that fixed it for me:

`               "controller": "https://<ip>443",
                "username": "<user>",
                "password": "<pass>",
                "site": "default",
                "unifios": true`

**Comment by hfagelnour** [comment]
Thx so much .... worked like a charm
