### ISSUE TITLE
UniFi Controller 6.0.45

### ISSUE THREAD

**Issue by jakudo** [oznu/homebridge-unifi-occupancy-sensor#32]
Hi,

I have na Cloud Key Gen 2 Plus with FW 2.0.27 and Controller 6.0.45, what address should I add then? It used to be http://192.168.1.42:443 (or 8443), but now it is not. I tried http://192.168.1.42/network/ however, that didn't work either.
Any suggestions?

Thanks,
Jakub

**Comment by hfagelnour** [comment]
This is the config entry u need to use:

   "controller": "https://controller IP",
                "username": "xxxxxxx",
                "password": "xxxxxxxx",
                "site": "default",
                "unifios": true

**Comment by jakudo** [comment]
I've also tried that, however, it says:
"Config Syntax Error
Config contains invalid JSON"

**Comment by hfagelnour** [comment]
If u paste the file here I could help.
Of course hiding the controller credentials

**Comment by jakudo** [comment]
This is what I have:

{
            "name": "Occupancy Sensor",
            "unifi": {
                "controller": "https://192.168.1.42",
                "username": "xxx",
                "password": "xxx",
                "site": "default"
            },
            "monitor": [
                {
                    "device": "3c:xxxxxxx"
                }
            ],
            "mode": "any",
            "interval": 1800,
            "accessory": "UniFi Occupancy Sensor"
        }

**Comment by hfagelnour** [comment]
Syntax is correct but u need to add

"unifios": true

Right after the “site” line

**Comment by jakudo** [comment]
I know, but when I add it I get it and try to save, it show the "Config syntax error" - "Config contains invalid JSON"
i tried:
"unifios": true
and
"unifios": "true"

non of them works.

**Comment by jakudo** [comment]
ok, found the mistake - forgot to ad coma ',' at the end of the line before.

However, still doesn't work. It doesn't show whether I'm (my phone) at home or not. I don't know how to check whther it is connected to the controller or not.

**Comment by hfagelnour** [comment]
Make sure ur phone MAC address is correct in the settings

**Comment by jakudo** [comment]
ok, not sure, what I've done wrong the first time, I deleted the plugin and install it again and it just started to work. Thanks a lot!
