### ISSUE TITLE
Unifi 5.6.36

### ISSUE THREAD

**Issue by Kimovitzh** [oznu/homebridge-unifi-occupancy-sensor#4]
Hi.

After I updated to controller version 5.6.36 it seems like it's not working any more.
Anyone else having this issue? 

Regards
Kim

**Comment by mneumark** [comment]
I don't know. I am on 5.6.36 and just tried to install this for the first time today. I'm getting the following:
```
[2018-4-11 09:35:26] [UniFi Occupancy Sensor] UniFi Events: Error (67) - Unexpected server response: 401
[2018-4-11 09:35:26] [UniFi Occupancy Sensor] UniFi Events: Disconnected (67) - Retry in 5000ms
```

**Comment by oznu** [comment]
I am using this without issue on 5.6.36. 

@mneumark I think the issue might be with the site name, which could be documented better.

The internal site name might not match the name you have allocated the site exactly. You can get the required site name by navigating to the site in the unifi controller then looking at the url bar:

```
https://unifi.com:8443/manage/site/mofkpypu/dashboard
```

In this case the site name is `mofkpypu` despite the actual site name being quite different.

Also make sure the user you're using does actually have access to the site, if using one user for multiple sites you can check the `Allow read only access to all sites` option.

**Comment by oznu** [comment]
Added note on site name to README.
