### ISSUE TITLE
WebSocket Failure Causes HB Crash

### ISSUE THREAD

**Issue by owine** [oznu/homebridge-unifi-occupancy-sensor#40]
**Describe The Bug:**

Intermitently, Homebridge will crash entirely with a log entry from the plugin about a WebSocket error. Homebridge runs successfully for extended periods of time and this crash happens at random points in time. The plugin does work and and function as expected.

**To Reproduce:**

Install/configure plugin
Wait undetermined amount of time
Observe Homebridge crash

**Expected behavior:**

Homebridge not crash

**Logs:**

```
Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/homebridge/node_modules/homebridge-unifi-occupancy-sensor/node_modules/ws/lib/websocket.js:367:19)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-unifi-occupancy-sensor/node_modules/unifi-events/index.js:90:21)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

**Homebridge Config:**

```json
{
    "name": "<redact>",
    "unifi": {
        "controller": "<controller ip>",
        "username": "<redact>",
        "password": "<redact>",
        "site": "default",
        "unifios": true
    },
    "monitor": [
        {
            "device": "<redact>"
        }
    ],
    "mode": "any",
    "watchGuests": true,
    "interval": 1800,
    "accessory": "UniFi Occupancy Sensor"
}
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v14.18.1
* **NPM Version**: v6.14.15
* **Homebridge Version**: v1.3.5
* **Homebridge Plugin Version**: v2.0.1
* **Homebridge Config UI X Plugin Version**: v4.41.2
* **Operating System**: Docker

**Comment by GraemeHalls** [comment]
I have the same issue with the latest version of Homebridge.
