### ISSUE TITLE
Can't figure out UniFi Controller Host Name

### ISSUE THREAD

**Issue by jakedeg** [oznu/homebridge-unifi-occupancy-sensor#41]
Hi There! Sorry for the noob question, but I'm fairly new to UniFi and I am so excited to find your homebridge plugin! It sounds like exactly what I'm looking for. 

I use a UDM as my controller. I access it locally via https://unifi.ui.com/ which is the domain it worked with out of the factory. I made a local view-only user for homebridge. 

I have been doing lots of research trying to figure out what you mean in the readme when you ask for `controller`?  I tried `https://unifi.ui.com/` and `https://unifi.ui.com:443` and `192.168.1.1` and none seem to work.  In lots of googling, and clicking around the UniFi Controller UI, I can't find anywhere to see or set a different domain/host. Maybe from [this reddit post](https://www.reddit.com/r/Ubiquiti/comments/mx6weu/udmpro_is_missing_the_controller_hostnameip_field/), it looks like this feature is missing from the UDM Pro and maybe the UDM too?

When I restart homebridge, the logs say:

```[MySensor] ERROR: Failed to check occupancy: Cannot read property 'length' of undefined```

I'm assuming that is because I have the controller URL wrong? 

Any ideas? Maybe this could lead to an update to the readme?

**Comment by hfagelnour** [comment]
U need to use the local IP u use to access the UDM controller.
192.168.x.1

**Comment by jakedeg** [comment]
Thanks for the reply!  I had tried `192.168.1.1`, and I got `ERROR: Failed to check occupancy: Error: getaddrinfo ENOTFOUND unifi` but now I just tried `https://192.168.1.1`, and it looks like it's working!
