### ISSUE TITLE
Doesn’t work at all 

### ISSUE THREAD

**Issue by asuatton** [oznu/homebridge-unifi-occupancy-sensor#43]
**Describe The Bug:**

Detect nothing     I try many Mac adress all present on UniFi but nothing.  
**To Reproduce:**

Just install it in a « normal » config and you will see.  I tryed in to different config (other network, other élément, other HomeBridge etc….) 
**Expected behaviors:**

Make it work !! 
**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your unifi username and password.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Plugin Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by NOTaMango** [comment]
What version of the network app? It does not work in the latest early access versions.
