### ISSUE TITLE
Trigger the sensor only when connected to a certain Access Point?

### ISSUE THREAD

**Issue by Cloudore** [oznu/homebridge-unifi-occupancy-sensor#5]
I think that'd match a lot with the purpose of the plug in. If I'm connected to the access point in my room then my room's occupancy should be triggered, if I am however connected to the one in the living room, then _it_ should be triggered and my room's should be off.

Just an enhancement idea! Thank you for the plug in

**Comment by devbobo** [comment]
@Cloudore that would need to be written as a `platform` plugin rather than an `accessory` plugin, as the plugin would need to be able to create an `accessory` for each AP that was found.

I'm going to have a shot at writing that, given what @oznu has already done.

**Comment by metainnova** [comment]
HI @Cloudore, same request here. I have 4 access points, and I want only to use the plugin with one access point. Is no option in the configuration to add in the Unifi request a filter for only one access point name?

Thanks a lot.

**Comment by oznu** [comment]
Done in v1.0.0
