### ISSUE TITLE
 Sensor "All or none present"

### ISSUE THREAD

**Issue by gold2605** [oznu/homebridge-unifi-occupancy-sensor#6]
Hello, is it possible to add a sensor for "All present" and "none present" for the devices to be monitored?

Many Thanks

**Comment by oznu** [comment]
Implemented.

Set `mode` to `any`, `all` or `none`. Defaults to `any` which is the normal/original behaviour.

```json
        {
            "accessory": "UniFi Occupancy Sensor",
            "name": "Sensor",
            "mode": "all",
            "watch": [
                "12:12:12:35:4b:12",
                "13:12:12:35:4b:12"
            ]
        }
```
