### ISSUE TITLE
Feature Request: Occupancy Sensor for each device or collection of devices

### ISSUE THREAD

**Issue by ethan4** [oznu/homebridge-unifi-occupancy-sensor#8]
Hi there,

This plugin is great and I will continue to use it but I'm wondering if it's much work to allow this to be split out by a single device or collection of devices so I can say "John" is home rather than "Someone" is home.

I tried another plugin along these lines but it didn't work for me and I like the approach of using the Unifi controller much better, here's the one I tried before https://github.com/PeteLawrence/homebridge-people

**Comment by oznu** [comment]
Hi @ethan4,

Does a setup like this do what you want?

https://github.com/oznu/homebridge-unifi-occupancy-sensor/issues/1#issuecomment-333694893

**Comment by ethan4** [comment]
Yes that's perfect! Thanks :)
