### ISSUE TITLE
Error at Starting Homebridge with Unifi Sensor

### ISSUE THREAD

**Issue by tStaiger** [oznu/homebridge-unifi-occupancy-sensor#9]
When I start the homebridge with the config 

`{
                "accessory": "UniFiOccupancySensor",
                "name": "Occupancy Sensor",
                "unifi": {
                        "controller": "https://localhost:8443",
                        "username": "xxxx",
                        "password": "xxxx;",
                        "site": "default",
                        "secure": false
                 },
                "watch": ["xx:xx:xx:xx:xx:x"],
                "watchGuests": true,
                "mode": "any"
        }`

the following Error occurs: 
`Error: The requested accessory 'UniFi Occupancy Sensor' was not registered by any plugin.`

Do you have any solution for this?

**Comment by oznu** [comment]
Hi @tStaiger,

The accessory name is incorrect in your config.

Change: `"accessory": "UniFiOccupancySensor"` to `"accessory": "UniFi Occupancy Sensor"`.

**Comment by tStaiger** [comment]
I tried it with `"accessory": "UniFi Occupancy Sensor"`. But that didn't work either.

**Comment by oznu** [comment]
In that case make sure it's installed globally:

```
npm install -g homebridge-unifi-occupancy-sensor
```

**Comment by tStaiger** [comment]
Perfect. It worked. But now an other error occurred. When I start it with a service `systemctl start homebridge` ist starts but exists immediately. When I start it just by calling `homebridge` it works. Do you have a solution?

**Comment by oznu** [comment]
What do the logs say?

```
journalctl -u homebridge
```

**Comment by tStaiger** [comment]
`     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:88:38)
Jun 13 09:26:37 raspberrypi homebridge[2495]:     at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:267:42)
Jun 13 09:26:37 raspberrypi homebridge[2495]:     at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
Jun 13 09:26:37 raspberrypi homebridge[2495]: Error: The requested accessory 'UniFi Occupancy Sensor' was not registered by any plugin.
Jun 13 09:26:37 raspberrypi homebridge[2495]:             ^
Jun 13 09:26:37 raspberrypi homebridge[2495]:       throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
Jun 13 09:26:37 raspberrypi homebridge[2495]: /usr/lib/node_modules/homebridge/lib/api.js:64
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] [Temperatur & Luftfeuchtigkeit] Initializing Hygrotermograph accessory...
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] [Yamaha AV] Initializing YamahaScene accessory...
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] Loading 3 accessories...
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] [Config] Initializing config platform...
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] [HomeMatic CCU] Fetching Homematic devices...
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] [HomeMatic CCU] local ip used : 192.168.10.27. you may change that with local_ip parameter in config
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] [HomeMatic CCU] init RPC for BidCos-RF.
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] [HomeMatic CCU] using binrpc for communication with BidCos-RF
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] [HomeMatic CCU] will connect to your ccu at 192.168.10.23
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] [HomeMatic CCU] Homematic Plugin Version 0.0.97
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] [HomeMatic CCU] Initializing HomeMatic platform...
Jun 13 09:26:37 raspberrypi homebridge[2495]: [2018-6-13 09:26:37] Loading 3 platforms...`

**Comment by oznu** [comment]
Strange that's it's working using the `homebridge` command directly.

Let's check the plugin got installed in the correct location, is it listed when you run this?

```
ls -la /usr/lib/node_modules
```

**Comment by tStaiger** [comment]
No. It's not listed.

**Comment by oznu** [comment]
I'm guessing homebridge is? Are you running `nvm` (node version manager) or something like that?

Either way, doing this should install it in the right place:

```
cd /usr/lib/node_modules
npm install homebridge-unifi-occupancy-sensor
```

**Comment by tStaiger** [comment]
Now it works. Thanks!

**Comment by oznu** [comment]
Great, you should probably figure out why `npm install -g` didn't actually install it in the global modules directory, but I'll leave that to you 😄.
